version: 2

# CommonJS
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  target-branch: "master"
  labels:
    - dependencies
    - CJS
  ignore:
    - dependency-name: "mocha"
      update-types: [ "version-update:semver-major" ]

# TypeScript Module
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  target-branch: "es-module"
  labels:
    - dependencies
    - ESM
