version: 2

updates:

# ECMAScript Module (ESM)
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  target-branch: "master"
  labels:
    - dependencies
