language: node_js
node_js:
 - "4"
 - "6"
 - "7"
 - "8"
 - "9"
 - "10"
install:
 - npm install
 - npm run compile
script:
 - npm run lint
 - npm run test

jobs:
  include:
    - stage: after_success
      script: npm run coveralls
      node_js: 9
