language: node_js
node_js:
 - "6"
 - "7"
 - "8"
 - "9"
 - "10"
 - "11"
install:
 - yarn install
 - yarn run compile
script:
 - yarn run lint-ts
 - yarn run lint-md
 - yarn run test

jobs:
  include:
    - stage: after_success
      script:
      - yarn install
      - yarn run compile
      - yarn run coveralls
      node_js: 9
